/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2020-03-24 20:12:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.google.gson.Gson;
import com.google.gson.JsonObject;
import java.util.Iterator;
import com.dao.Dao;
import java.util.List;

public final class agraphs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("<meta name=\"description\" content=\"\" />\r\n");
      out.write("<link href=\"http://fonts.googleapis.com/css?family=Didact+Gothic\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<link href=\"default.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"main.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"fonts.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div   style=\"padding-top: 10px; padding-left: 0px;\">\r\n");
      out.write("\t\t<div id=\"header\" class=\"container\">\r\n");
      out.write("\t\t\t<div id=\"logo\" style=\"width: 600px; height: 100%; top: 0em;\">\r\n");
      out.write("\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"font-size: 30px;\">A Network Coding and DES\r\n");
      out.write("\t\t\t\t\t\tBased Dynamic Encryption Scheme for Moving Target Defense</a>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"menu\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"ahome.jsp\" accesskey=\"1\" title=\"\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"aowner.jsp\" accesskey=\"2\" title=\"\">Owner</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"auser.jsp\" accesskey=\"3\" title=\"\">User</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"afiles.jsp\" accesskey=\"4\" title=\"\">Files</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"akey.jsp\" accesskey=\"4\" title=\"\">Keys</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"attack.jsp\" accesskey=\"4\" title=\"\">Attack</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.html\" accesskey=\"5\" title=\"\">Logout</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"banner\" class=\"container\" style=\"padding-top: 100px;\">\r\n");
      out.write("\t\t\t<div class=\"title\">\r\n");
      out.write("\t\t<div id=\"chartContainer\" style=\"height: 370px;\" class=\"tbox2 boxC\"></div>\r\n");
      out.write("\t\t<div id=\"chartContainer1\" style=\"height: 370px;\" class=\"tbox1 boxA\"></div>\r\n");
      out.write("<script src=\"https://canvasjs.com/assets/script/canvasjs.min.js\"></script>\t\t\r\n");
      out.write(" \r\n");

Gson gsonObj = new Gson();
Map<Object,Object> map = null;
List<Map<Object,Object>> list = new ArrayList<Map<Object,Object>>();
String sql = "select fid from data1";
List<String> lt = Dao.getFid(sql);
Iterator<String> itr = lt.iterator();
while(itr.hasNext()){
	String fid = itr.next();
	sql = "select count(*) from attack where fid='"+fid+"'";
	int count = Dao.getCount(sql);
map = new HashMap<Object,Object>(); map.put("label", fid); map.put("y", count); list.add(map);
}
String dataPoints = gsonObj.toJson(list);
List<Map<Object,Object>> list1 = new ArrayList<Map<Object,Object>>();
sql = "select fid from data1";
List<String> lt1 = Dao.getFid(sql);
Iterator<String> itr1 = lt1.iterator();
while(itr1.hasNext()){
	String fid = itr1.next();
	sql = "select count(*) from keyrequest where fid='"+fid+"'";
	int count = Dao.getCount(sql);
map = new HashMap<Object,Object>(); map.put("label", fid); map.put("y", count); list1.add(map);
}
String dataPoints1 = gsonObj.toJson(list1);

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("window.onload = function() { \r\n");
      out.write(" \r\n");
      out.write("var chart = new CanvasJS.Chart(\"chartContainer\", {\r\n");
      out.write("\ttheme: \"light2\",\r\n");
      out.write("\tanimationEnabled: true,\r\n");
      out.write("\texportFileName: \"New Year Resolutions\",\r\n");
      out.write("\texportEnabled: true,\r\n");
      out.write("\ttitle:{\r\n");
      out.write("\t\ttext: \"Attacked Files\"\r\n");
      out.write("\t},\r\n");
      out.write("\tdata: [{\r\n");
      out.write("\t\ttype: \"pie\",\r\n");
      out.write("\t\tshowInLegend: true,\r\n");
      out.write("\t\tlegendText: \"{label}\",\r\n");
      out.write("\t\ttoolTipContent: \"{label}: <strong>{y}%</strong>\",\r\n");
      out.write("\t\tindexLabel: \"{label} {y}\",\r\n");
      out.write("\t\tdataPoints : ");
out.print(dataPoints);
      out.write("\r\n");
      out.write("\t}]\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("var chart1 = new CanvasJS.Chart(\"chartContainer1\", {\r\n");
      out.write("\ttheme: \"light2\",\r\n");
      out.write("\tanimationEnabled: true,\r\n");
      out.write("\texportFileName: \"New Year Resolutions\",\r\n");
      out.write("\texportEnabled: true,\r\n");
      out.write("\ttitle:{\r\n");
      out.write("\t\ttext: \"Request Files\"\r\n");
      out.write("\t},\r\n");
      out.write("\tdata: [{\r\n");
      out.write("\t\ttype: \"pie\",\r\n");
      out.write("\t\tshowInLegend: true,\r\n");
      out.write("\t\tlegendText: \"{label}\",\r\n");
      out.write("\t\ttoolTipContent: \"{label}: <strong>{y}%</strong>\",\r\n");
      out.write("\t\tindexLabel: \"{label} {y}\",\r\n");
      out.write("\t\tdataPoints : ");
out.print(dataPoints1);
      out.write("\r\n");
      out.write("\t}]\r\n");
      out.write("});\r\n");
      out.write("chart.render();\r\n");
      out.write("chart1.render();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t\t<div id=\"three-column\" class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"title\">\r\n");
      out.write("\t\t\t\t<h2>Feugiat lorem ipsum dolor sed veroeros</h2>\r\n");
      out.write("\t\t\t\t<span class=\"byline\">Donec leo, vivamus fermentum nibh in\r\n");
      out.write("\t\t\t\t\taugue praesent a lacus at urna congue</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"boxA\">\r\n");
      out.write("\t\t\t\t<p>Phasellus pellentesque, ante nec iaculis dapibus, eros justo\r\n");
      out.write("\t\t\t\t\tauctor lectus, a lobortis lorem mauris quis nunc. Praesent\r\n");
      out.write("\t\t\t\t\tpellentesque facilisis elit. Class aptent taciti sociosqu ad\r\n");
      out.write("\t\t\t\t\ttorquent per conubia nostra.</p>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"button button-alt\">More Info</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"boxB\">\r\n");
      out.write("\t\t\t\t<p>Etiam neque. Vivamus consequat lorem at nisl. Nullam wisi a\r\n");
      out.write("\t\t\t\t\tsem semper eleifend. Donec mattis. Phasellus pellentesque, ante nec\r\n");
      out.write("\t\t\t\t\tiaculis dapibus, eros justo auctor lectus, a lobortis lorem mauris\r\n");
      out.write("\t\t\t\t\tquis nunc.</p>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"button button-alt\">More Info</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"boxC\">\r\n");
      out.write("\t\t\t\t<p>Aenean lectus lorem, imperdiet at, ultrices eget, ornare et,\r\n");
      out.write("\t\t\t\t\twisi. Pellentesque adipiscing purus. Phasellus pellentesque, ante\r\n");
      out.write("\t\t\t\t\tnec iaculis dapibus, eros justo auctor lectus, a lobortis lorem\r\n");
      out.write("\t\t\t\t\tmauris quis nunc.</p>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"button button-alt\">More Info</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"welcome\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"title\">\r\n");
      out.write("\t\t\t\t<h2>Fusce ultrices fringilla metus</h2>\r\n");
      out.write("\t\t\t\t<span class=\"byline\">Donec leo, vivamus fermentum nibh in\r\n");
      out.write("\t\t\t\t\taugue praesent a lacus at urna congue</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\tLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>\r\n");
      out.write("\t\t\t<ul class=\"actions\">\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"button\">Etiam posuere</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"copyright\" class=\"container\">\r\n");
      out.write("\t\t<p> &copy; All rights reserved | Designed by DCET 2020.</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
